### ISSUE TITLE
 'tensorflow' is not a package

### ISSUE THREAD

**Issue by mircare** [dhasl002/3DUnet_Cryo-Em#2]
Hi there,
I would recommend renaming the python files to anything different than the used libraries as if I run `python3 tensorflow.py` it will break the shell session on Linux and won't work:

> Traceback (most recent call last):
>   File "tensorflow.py", line 1, in <module>
>     import tensorflow as tf
>   File "Research-DeepLearning/tensorflow.py", line 3, in <module>
>     from tensorflow.python import debug as tf_debug
> ImportError: No module named 'tensorflow.python'; 'tensorflow' is not a package

If I rename tensorflow.py in anything else and, run in a new shel session, it will work just fine:
`mv tensorflow.py asd.py; python3 asd.py `
> python3 asd.py
> 2018-04-25 23:44:46.483588: I tensorflow/core/platform/cpu_feature_guard.cc:140]
> [..]

**Comment by dhasl002** [comment]
Thank you! Just fixed it
